In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('clientes_sujo.csv', sep=';', encoding='utf-8')

df_clientes = pd.DataFrame(df)

In [4]:
df_clientes

,id_cliente,nome,email,dt_cadastro,valor_compra,cidade,status
0,1001,Ana Souza,ana.souza@email.com,2026-01-15,"R$ 1.250,50",São Paulo,ATIVO
1,1002,carlos LIMA,carlos.lima@email.com,16/01/2026,"R$ 980,00",sao paulo,Ativo
2,1003,Beatriz Alves,beatriz.alves@email,2026-01-17,"R$ 2.310,90",Campinas,ativo
3,1004,Daniel Rocha,daniel.rocha@email.com,18/01/2026,NaN,Santos,INATIVO
4,1002,Carlos Lima,carlos.lima@email.com,16/01/2026,"R$ 980,00",São Paulo,Ativo
5,1005,Eduarda Martins,NaN,2026-01-20,"R$ 450,00",SÃO PAULO,ativo
6,1006,fábio Nunes,fabio.nunes@email.com,21/01/2026,"R$ 1.000,00",Guarulhos,Ativo
7,abc,Gabriela Dias,gabi.dias@email.com,2026-01-22,"R$ 300,00",Campinas,ATIVO
8,1008,Henrique Costa,henrique.costa@email.com,32/01/2026,"R$ 720,75",Santos,ativo
9,1009,Isabela Ramos,isabela.ramos@email.com,2026-01-25,"R$ 15.000,00",Sao Paulo,Inativo
10,1010,NaN,joao.pereira@email.com,26/01/2026,"R$ 610,00",Guarulhos,ATIVO
11,1011,Karen Oliveira,karen.o@email.com,2026-01-27,"-R$ 50,00",campinas,ativo
12,1012,Lucas Prado,lucas.prado@email.com,NaN,"R$ 830,20",Santos,Ativo

In [6]:
df_clientes.describe()

,id_cliente,nome,email,dt_cadastro,valor_compra,cidade,status
count,13,12,12,12,12,13,13
unique,12,12,11,11,11,8,6
top,1002,Ana Souza,carlos.lima@email.com,16/01/2026,"R$ 980,00",Santos,Ativo
freq,2,1,2,2,2,3,4

In [7]:
df_clientes = df_clientes.drop_duplicates()

In [ ]:
df_clientes = df_clientes[cidade](
    [sao paulo] == [São Paulo]

NameError: name 'cidade' is not defined